image: node:latest

cache:
  paths:
    - node_modules/


stages:
  - build
  - test
  - package
  - pre_release
  - release


build:
  stage: build
  script: 
    - npm install
  only:
   - merge_requests
   - develop
   - main

test:
  stage: test
  script:
    - npm run test
  needs:
    - job: build
  only:
   - main
   - merge_requests
   - develop

package:
  stage: package
  script:
    - apt update && apt install zip unzip -y
    - zip -r $CI_PROJECT_NAME.zip $CI_PROJECT_DIR
    - ls -l 
  artifacts:
    paths:
      - $CI_PROJECT_NAME.zip
  needs:
    - job: test
  only:
    - main

pre_release:
  stage: pre_release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "EXTRA_DESCRIPTION=some message" >> variables.env
    - echo "TAG=v$(cat VERSION)" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: pre_release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo 'Running release'
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'
    tag_name: '$TAG'  
    ref: '$CI_COMMIT_SHA'